# info
title: Jay Bulsara
author: Jay Bulsara
email: jay@jaybulsara.dev
description: >
  This is my website. If it looks bad, email me about it!

# social links
url: "https://jaybulsara.dev"
github_username: jaxbulsara
rss: rss

# theme
minima:
  date_format: "%b %-d, %Y"

# build
theme: minima
destination: docs
show_excerpts: true
exclude:
  - .liquidrc
  - README.md
  - build.sh
  - serve.sh
  - shell.sh
  - workspace.code-workspace
plugins:
  - jekyll-feed
  - jekyll-seo-tag
